version: 2.1

workflows:
  version: 2
  check:
    jobs:
      - ci

jobs:
  ci:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - run: go version
      - run: 'make lint'
      - run: 'make test'
      - run: 'make build'
